//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogNotificationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogNotificationType()
        {
            this.NotificationDestination = new HashSet<NotificationDestination>();
        }
    
        public int IdNotificationType { get; set; }
        public string NotificationType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public string RegularExpression { get; set; }
    
        public virtual NotificationConfig NotificationConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationDestination> NotificationDestination { get; set; }
    }
}
