//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationConfig
    {
        public int IdTypeNotification { get; set; }
        public string ProvaiderNotification { get; set; }
        public string JsonConfig { get; set; }
    
        public virtual CatalogNotificationType CatalogNotificationType { get; set; }
    }
}
