//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotificationDbEntities : DbContext
    {
        public NotificationDbEntities(String conectionString)
            : base(conectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatalogNotificationType> CatalogNotificationType { get; set; }
        public virtual DbSet<NotificationConditions> NotificationConditions { get; set; }
        public virtual DbSet<NotificationConfig> NotificationConfig { get; set; }
        public virtual DbSet<NotificationDestination> NotificationDestination { get; set; }
        public virtual DbSet<NotificationEvents> NotificationEvents { get; set; }
        public virtual DbSet<NotificationLog> NotificationLog { get; set; }
        public virtual DbSet<NotificationMessageBase> NotificationMessageBase { get; set; }
        public virtual DbSet<NotificationQueryCondition> NotificationQueryCondition { get; set; }
        public virtual DbSet<NotificationTableDestination> NotificationTableDestination { get; set; }
    }
}
