//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDestination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationDestination()
        {
            this.NotificationLog = new HashSet<NotificationLog>();
        }
    
        public int IdNotificationCondtion { get; set; }
        public int IdNotificationType { get; set; }
        public string TableName { get; set; }
        public string TableKeys { get; set; }
        public string BaseSend { get; set; }
        public bool Notify { get; set; }
        public Nullable<int> IdMessageBase { get; set; }
        public string MessageSpecifict { get; set; }
        public string TitleSpecifict { get; set; }
        public string ParamsMessageBase { get; set; }
        public string ParamsTitleBase { get; set; }
    
        public virtual CatalogNotificationType CatalogNotificationType { get; set; }
        public virtual NotificationConditions NotificationConditions { get; set; }
        public virtual NotificationMessageBase NotificationMessageBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationLog> NotificationLog { get; set; }
    }
}
