//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTableDestination
    {
        public int IdNotificationTableDestination { get; set; }
        public string TableDestination { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
