//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationQueryCondition
    {
        public int IdQueryCondition { get; set; }
        public int IdNotificationCondition { get; set; }
        public string QueryCondition { get; set; }
        public string ParameterDimical { get; set; }
        public System.DateTime CreateAt { get; set; }
        public System.DateTime UpdateAt { get; set; }
    
        public virtual NotificationConditions NotificationConditions { get; set; }
    }
}
