//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationFromSytimeSQL.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int IdNotificationCondition { get; set; }
        public string TaleName { get; set; }
        public string TableKeys { get; set; }
        public int IdTypeNotification { get; set; }
        public string EventName { get; set; }
        public System.DateTime DateSend { get; set; }
        public string TableEvent { get; set; }
        public string BaseSend { get; set; }
        public bool WasSend { get; set; }
        public string TitleMessage { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
    
        public virtual NotificationDestination NotificationDestination { get; set; }
    }
}
