//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class abc_terceros
    {
        public decimal nit { get; set; }
        public string tipo { get; set; }
        public string clasificacion { get; set; }
        public decimal porcentaje_clasificacion { get; set; }
        public decimal valor_tercero { get; set; }
    }
}
