//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class bodegas
    {
        public short bodega { get; set; }
        public string descripcion { get; set; }
        public int centro { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string texto { get; set; }
        public string codigo_cliente { get; set; }
        public int id { get; set; }
        public Nullable<bool> es_punto_venta { get; set; }
        public string impresora { get; set; }
        public string departamento { get; set; }
        public string ciudad { get; set; }
        public Nullable<bool> autoretenedorica { get; set; }
        public Nullable<bool> es_bod_taller { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
        public Nullable<bool> Acepta_Ext { get; set; }
        public Nullable<int> Utilidad { get; set; }
        public string idSMD { get; set; }
        public string pais { get; set; }
        public Nullable<bool> demostracion { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<bool> es_bod_vehiculos { get; set; }
        public bool es_bodega_obsoleta { get; set; }
        public bool es_almacen { get; set; }
        public string inactiva { get; set; }
        public Nullable<int> BAC { get; set; }
        public string principal { get; set; }
        public string CodigoBIR_Renault { get; set; }
        public string cuentaGarantiaRenault { get; set; }
        public Nullable<bool> EsServicioRapido { get; set; }
        public string usa_rental { get; set; }
        public Nullable<int> idSede { get; set; }
        public string envia_distrinet { get; set; }
        public Nullable<byte> renault { get; set; }
        public Nullable<int> cod_concesionario { get; set; }
        public string unidad_negocio { get; set; }
    }
}
