//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DmsV1Entities : DbContext
    {
        public DmsV1Entities(String conectionstring)
           : base(conectionstring)
        {
            var type = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
            if (type == null)
                throw new Exception("Do not remove, ensures static reference to System.Data.Entity.SqlServer");
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abc_terceros> abc_terceros { get; set; }
        public virtual DbSet<bodegas> bodegas { get; set; }
        public virtual DbSet<referencias> referencias { get; set; }
        public virtual DbSet<referencias_imp> referencias_imp { get; set; }
        public virtual DbSet<tall_citas> tall_citas { get; set; }
        public virtual DbSet<tall_conceptos_operaciones> tall_conceptos_operaciones { get; set; }
        public virtual DbSet<tall_encabeza_orden> tall_encabeza_orden { get; set; }
        public virtual DbSet<tall_operarios> tall_operarios { get; set; }
        public virtual DbSet<terceros> terceros { get; set; }
        public virtual DbSet<vh_clase> vh_clase { get; set; }
        public virtual DbSet<vh_eventos> vh_eventos { get; set; }
        public virtual DbSet<vh_familias> vh_familias { get; set; }
        public virtual DbSet<vh_marcas> vh_marcas { get; set; }
        public virtual DbSet<vh_modelo> vh_modelo { get; set; }
        public virtual DbSet<vh_modelo_ano> vh_modelo_ano { get; set; }
        public virtual DbSet<vh_modelo_taller> vh_modelo_taller { get; set; }
        public virtual DbSet<vh_terceros> vh_terceros { get; set; }
        public virtual DbSet<vh_tipo_carroceria> vh_tipo_carroceria { get; set; }
        public virtual DbSet<vh_tipo_flotas> vh_tipo_flotas { get; set; }
        public virtual DbSet<vh_tipo_modelo> vh_tipo_modelo { get; set; }
        public virtual DbSet<VH_tipo_pintura> VH_tipo_pintura { get; set; }
        public virtual DbSet<y_ciudades> y_ciudades { get; set; }
        public virtual DbSet<y_departamentos> y_departamentos { get; set; }
        public virtual DbSet<y_paises> y_paises { get; set; }
        public virtual DbSet<NotificationSystime> NotificationSystime { get; set; }
    }
}
