//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSystime
    {
        public int IdNotificationSystime { get; set; }
        public string TableName { get; set; }
        public string JsonKeys { get; set; }
        public string EventTable { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
