//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencias_imp
    {
        public string codigo { get; set; }
        public string pos_arancel { get; set; }
        public Nullable<decimal> costo_unitario_FOB { get; set; }
        public Nullable<float> gravamen { get; set; }
        public string explicacion { get; set; }
        public string serie { get; set; }
        public string chasis { get; set; }
        public string motor { get; set; }
        public Nullable<short> modelo_ano { get; set; }
        public string tipo_motor { get; set; }
        public string manifiesto { get; set; }
        public Nullable<decimal> nit_prenda { get; set; }
        public Nullable<decimal> nit_adicional_1 { get; set; }
        public Nullable<decimal> nit_adicional_2 { get; set; }
        public Nullable<decimal> nit_adicional_3 { get; set; }
        public Nullable<int> horas_uso { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public string placa { get; set; }
        public Nullable<System.DateTime> fecha_fin_garantia { get; set; }
        public Nullable<decimal> nit_comprador { get; set; }
        public Nullable<byte> comprado { get; set; }
        public string id_modano { get; set; }
        public string color { get; set; }
        public Nullable<System.DateTime> fecha_manifiesto { get; set; }
        public string garantia { get; set; }
        public Nullable<byte> tipo_venta { get; set; }
        public Nullable<byte> plan_venta { get; set; }
        public Nullable<byte> usado_comprado { get; set; }
        public Nullable<byte> usado_retomado { get; set; }
        public Nullable<byte> usado_consignado { get; set; }
        public Nullable<byte> recibido_canje { get; set; }
        public Nullable<byte> entregado_canje { get; set; }
        public Nullable<byte> vendido { get; set; }
        public Nullable<int> asignacion { get; set; }
        public Nullable<bool> entregado_cliente { get; set; }
        public Nullable<bool> entregado_matricula { get; set; }
        public Nullable<decimal> reservado { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public Nullable<System.DateTime> fin_reserva { get; set; }
        public Nullable<decimal> costo_alistamiento { get; set; }
        public Nullable<decimal> costo_compra { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public string codigo_concesionario { get; set; }
        public string modelo_taller { get; set; }
        public string OtroServicio { get; set; }
        public string ciudad_placa { get; set; }
        public Nullable<System.DateTime> fecha_cambio_km { get; set; }
        public string carpeta { get; set; }
        public Nullable<decimal> nit_aseguradora { get; set; }
        public Nullable<System.DateTime> fec_vencimiento_seg { get; set; }
        public string Levante { get; set; }
        public Nullable<int> Año_Fab { get; set; }
        public Nullable<decimal> Oferta { get; set; }
        public string Color_Interno { get; set; }
        public string Codigo_Radio { get; set; }
        public Nullable<short> Tiempo_Garantia { get; set; }
        public Nullable<int> Km_Garantia { get; set; }
        public string NumSOAT { get; set; }
        public Nullable<int> Razon_Cambio_Prop { get; set; }
        public Nullable<System.DateTime> fecha_expedicion_manifiesto { get; set; }
        public Nullable<System.DateTime> fin_asignacion { get; set; }
        public string Refrendo { get; set; }
        public string requiere_registro { get; set; }
        public string registro_importacion { get; set; }
        public Nullable<System.DateTime> vencimiento_registro { get; set; }
        public Nullable<decimal> cantidad_registro { get; set; }
        public Nullable<decimal> costo_registro { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string moneda { get; set; }
        public Nullable<System.DateTime> fecha_aprobado { get; set; }
        public string pos_arancel_internacional { get; set; }
        public Nullable<decimal> nit_usuario { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string sinLimiteDekmEnGtia { get; set; }
        public Nullable<byte> puertas { get; set; }
        public string homologacion { get; set; }
        public string ciudad_manifiesto { get; set; }
        public Nullable<decimal> Revista { get; set; }
        public string cabina { get; set; }
        public string tipoPintura { get; set; }
        public Nullable<System.DateTime> fecha_cambio_horas_uso { get; set; }
        public Nullable<int> consecutivo_compra { get; set; }
        public Nullable<System.DateTime> fecha_obligatorio { get; set; }
        public Nullable<System.DateTime> fecha_gases { get; set; }
        public Nullable<System.DateTime> fecha_tecnico_mecanica { get; set; }
        public string tipo_caja { get; set; }
        public string linea_chevystar { get; set; }
        public string blindado { get; set; }
        public string Convertido_gas { get; set; }
        public string documento_relacionado { get; set; }
        public string motivo_pedido { get; set; }
        public string bitvta { get; set; }
        public string numero_inserto { get; set; }
        public Nullable<bool> scope { get; set; }
        public Nullable<bool> flotilla_sofasa { get; set; }
        public string fabricacion_sofasa { get; set; }
        public string estado_sofasa { get; set; }
        public Nullable<int> concesionario_comprador { get; set; }
    
        public virtual referencias referencias { get; set; }
        public virtual vh_modelo_ano vh_modelo_ano { get; set; }
    }
}
