//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_encabeza_orden
    {
        public int numero { get; set; }
        public Nullable<decimal> nit { get; set; }
        public string serie { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> entrada { get; set; }
        public Nullable<decimal> vendedor { get; set; }
        public Nullable<System.DateTime> promesa_entrega { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> aseguradora { get; set; }
        public string poliza { get; set; }
        public string siniestro { get; set; }
        public Nullable<decimal> deducible { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<System.DateTime> entrega { get; set; }
        public string notas { get; set; }
        public string tipo { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public Nullable<int> horas_uso { get; set; }
        public short bodega { get; set; }
        public string entrego { get; set; }
        public bool facturada { get; set; }
        public string rombo { get; set; }
        public bool facturo_deducible { get; set; }
        public string ocupada_por { get; set; }
        public Nullable<short> horas { get; set; }
        public bool anulada { get; set; }
        public string pc { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> ultima_modificacion { get; set; }
        public string condicion_pago { get; set; }
        public string rombo_usado { get; set; }
        public string ubicacion { get; set; }
        public string tipo_deducible { get; set; }
        public Nullable<int> numero_deducible { get; set; }
        public Nullable<System.DateTime> fecha_hora_entrega_real { get; set; }
        public string usuario_entrega_real { get; set; }
        public string pc_entrega_real { get; set; }
        public Nullable<int> numero_entrega { get; set; }
        public string tipo_orden { get; set; }
        public string bloqueada { get; set; }
        public Nullable<short> codigo_direccion { get; set; }
        public Nullable<short> spid { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public Nullable<int> km_anterior { get; set; }
        public int id { get; set; }
        public Nullable<int> numero_orden_anulada { get; set; }
        public Nullable<int> cotizacion { get; set; }
        public Nullable<decimal> asesor_aseguradora { get; set; }
        public string notas2 { get; set; }
        public string usuario_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_hora_autoriza { get; set; }
        public Nullable<short> razon { get; set; }
        public Nullable<short> Recepcion_Interactiva { get; set; }
        public string procesadaPlano { get; set; }
        public Nullable<int> horas_uso_anterior { get; set; }
        public string es_ppc { get; set; }
        public Nullable<float> porce_apoyo_1 { get; set; }
        public Nullable<float> porce_apoyo_2 { get; set; }
        public Nullable<float> porce_apoyo_3 { get; set; }
        public Nullable<System.DateTime> fecha_cierre_final { get; set; }
        public string perdida_total { get; set; }
        public string notas3 { get; set; }
        public string cita { get; set; }
    
        public virtual referencias referencias { get; set; }
    }
}
