//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_citas
    {
        public int id_cita { get; set; }
        public short bodega { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public string estado_cita { get; set; }
        public string descripcion_estado { get; set; }
        public System.DateTime fecha_hora_ini { get; set; }
        public System.DateTime fecha_hora_fin { get; set; }
        public byte hora { get; set; }
        public byte minutos { get; set; }
        public Nullable<int> duracion_minutos { get; set; }
        public string codigo_veh { get; set; }
        public string placa { get; set; }
        public Nullable<decimal> nit { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<decimal> nit_nuevo { get; set; }
        public string nombre_encargado { get; set; }
        public string telefonos { get; set; }
        public string notas { get; set; }
        public string modelo_veh { get; set; }
        public Nullable<int> ano_veh { get; set; }
        public Nullable<System.DateTime> fecha_hora_asistio { get; set; }
        public Nullable<int> numero_orden_taller { get; set; }
        public string usuario { get; set; }
        public string pc { get; set; }
        public string modulo { get; set; }
        public string razon { get; set; }
        public string jefe_unidad { get; set; }
        public string tipo_llamada { get; set; }
    
        public virtual referencias referencias { get; set; }
        public virtual terceros terceros { get; set; }
    }
}
