//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class terceros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public terceros()
        {
            this.referencias = new HashSet<referencias>();
            this.tall_citas = new HashSet<tall_citas>();
        }
    
        public decimal nit { get; set; }
        public Nullable<byte> digito { get; set; }
        public string nombres { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono_1 { get; set; }
        public string telefono_2 { get; set; }
        public string fax { get; set; }
        public string apartado_aereo { get; set; }
        public string tipo_identificacion { get; set; }
        public string pais { get; set; }
        public bool gran_contribuyente { get; set; }
        public bool autoretenedor { get; set; }
        public Nullable<byte> bloqueo { get; set; }
        public string notas { get; set; }
        public Nullable<byte> lista { get; set; }
        public string concepto_1 { get; set; }
        public string concepto_2 { get; set; }
        public string concepto_3 { get; set; }
        public string concepto_4 { get; set; }
        public string concepto_5 { get; set; }
        public string concepto_6 { get; set; }
        public string concepto_7 { get; set; }
        public string concepto_8 { get; set; }
        public string concepto_9 { get; set; }
        public string concepto_10 { get; set; }
        public string mail { get; set; }
        public byte pos_num { get; set; }
        public string regimen { get; set; }
        public Nullable<decimal> cupo_credito { get; set; }
        public decimal nit_real { get; set; }
        public string condicion { get; set; }
        public Nullable<decimal> vendedor { get; set; }
        public Nullable<float> fletes { get; set; }
        public string es_excento_iva { get; set; }
        public string contacto_1 { get; set; }
        public string contacto_2 { get; set; }
        public string formato_factura { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<byte> formato_copias { get; set; }
        public string tipo_factura { get; set; }
        public Nullable<short> dias_gracia { get; set; }
        public string solo_contado { get; set; }
        public Nullable<float> descuento_fijo { get; set; }
        public string excluir_tabla_desc { get; set; }
        public Nullable<int> centro_fijo { get; set; }
        public string exportado { get; set; }
        public string factor_o_lista { get; set; }
        public Nullable<int> codigo_ica { get; set; }
        public Nullable<float> descuento_fijo2 { get; set; }
        public string y_dpto { get; set; }
        public string y_ciudad { get; set; }
        public string concepto_11 { get; set; }
        public string concepto_12 { get; set; }
        public string concepto_13 { get; set; }
        public string concepto_14 { get; set; }
        public string concepto_15 { get; set; }
        public string concepto_16 { get; set; }
        public string concepto_17 { get; set; }
        public string concepto_18 { get; set; }
        public string concepto_19 { get; set; }
        public string concepto_20 { get; set; }
        public Nullable<float> descuento_fijo_prov { get; set; }
        public string solo_contado_compra { get; set; }
        public string celular { get; set; }
        public Nullable<System.DateTime> fecha_cambio_razon { get; set; }
        public string razon_comercial { get; set; }
        public int id { get; set; }
        public Nullable<decimal> minimo_ret_vtas { get; set; }
        public string y_pais { get; set; }
        public string ext_1 { get; set; }
        public string codigo_alterno { get; set; }
        public string tipo_devolucion { get; set; }
        public string Usuario { get; set; }
        public Nullable<short> tipo_direccion { get; set; }
        public Nullable<int> id_definicion_tributaria_tipo { get; set; }
        public Nullable<bool> Separa_Iva { get; set; }
        public Nullable<bool> Separa_Negocio { get; set; }
        public Nullable<bool> Solo_Remision { get; set; }
        public Nullable<bool> Devolver_Prod { get; set; }
        public string departamento { get; set; }
        public string ciudad2 { get; set; }
        public Nullable<short> dias_recibo_caja { get; set; }
        public string Runt { get; set; }
        public Nullable<System.DateTime> Fecha_Runt { get; set; }
        public string estado_civil { get; set; }
        public Nullable<decimal> cupo_credito_vh { get; set; }
        public string estrato { get; set; }
        public string paginaweb { get; set; }
        public string area_labora { get; set; }
        public string cargo { get; set; }
        public string ext2 { get; set; }
        public string celular2 { get; set; }
        public string email2 { get; set; }
        public Nullable<float> otro_descuento { get; set; }
        public string no_regulados { get; set; }
        public Nullable<float> descuento_financiero { get; set; }
        public string actividad_cree { get; set; }
        public string es_excento_cree_ventas { get; set; }
        public string sincronizado { get; set; }
        public string codigoPostal { get; set; }
        public string mail_adicional { get; set; }
        public string ean { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fecha_cumple_ter { get; set; }
        public string tieneRUT { get; set; }
        public string codigoActividadEconomica { get; set; }
        public string ftoCopia_factura { get; set; }
        public string formatoRemision { get; set; }
        public string es_extranet { get; set; }
        public string copiaRemision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referencias> referencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_citas> tall_citas { get; set; }
        public virtual tall_operarios tall_operarios { get; set; }
    }
}
