//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class vh_modelo_ano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vh_modelo_ano()
        {
            this.referencias_imp = new HashSet<referencias_imp>();
        }
    
        public string id_modano { get; set; }
        public string modelo { get; set; }
        public int ano { get; set; }
        public decimal precio_lista { get; set; }
        public Nullable<decimal> precio_anterior { get; set; }
        public Nullable<System.DateTime> ultimo_cambio_precio { get; set; }
        public Nullable<decimal> maximo_vl_dcto { get; set; }
        public Nullable<float> maximo_porc_dcto { get; set; }
        public short codigo_iva { get; set; }
        public short codigo_iva_compra { get; set; }
        public Nullable<decimal> valor_seguro { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
        public Nullable<decimal> costo_anterior { get; set; }
        public Nullable<float> alto { get; set; }
        public Nullable<float> ancho { get; set; }
        public Nullable<float> peso { get; set; }
        public Nullable<decimal> margen { get; set; }
        public Nullable<float> porc_margen { get; set; }
        public Nullable<float> porc_concesionario { get; set; }
        public Nullable<decimal> comision { get; set; }
        public Nullable<float> porc_comision { get; set; }
        public Nullable<float> largo { get; set; }
        public string tex1 { get; set; }
        public string tex2 { get; set; }
        public string tex3 { get; set; }
        public bool nuevo { get; set; }
        public int id { get; set; }
        public Nullable<decimal> km_dia { get; set; }
        public Nullable<decimal> soat { get; set; }
        public string descontinuado { get; set; }
        public Nullable<decimal> precio_final_impoconsumo { get; set; }
        public Nullable<decimal> matricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referencias_imp> referencias_imp { get; set; }
        public virtual vh_modelo vh_modelo { get; set; }
    }
}
