//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class vh_modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vh_modelo()
        {
            this.vh_modelo_ano = new HashSet<vh_modelo_ano>();
        }
    
        public string modelo { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string grupo { get; set; }
        public string tipo { get; set; }
        public string clase { get; set; }
        public byte contable { get; set; }
        public float capacidad { get; set; }
        public string und_capacidad { get; set; }
        public Nullable<float> cilindraje { get; set; }
        public string servicio { get; set; }
        public string combustible { get; set; }
        public string origen { get; set; }
        public string descontinuado { get; set; }
        public string modelo_taller { get; set; }
        public byte[] foto_modelo { get; set; }
        public string homologacion { get; set; }
        public string adicional { get; set; }
        public string Tipo_Auto { get; set; }
        public string familia { get; set; }
        public string GrupoICE { get; set; }
        public string familiaVComercial { get; set; }
        public Nullable<bool> Modelo_Sofasa { get; set; }
    
        public virtual vh_clase vh_clase { get; set; }
        public virtual vh_marcas vh_marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vh_modelo_ano> vh_modelo_ano { get; set; }
        public virtual vh_tipo_modelo vh_tipo_modelo { get; set; }
    }
}
