//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class vh_modelo_taller
    {
        public string modelo_taller { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string grupo { get; set; }
        public string familia { get; set; }
        public string familiaVersionComercial { get; set; }
        public string esModeloSofasa { get; set; }
    }
}
