//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDataAccessFromSystime.Erps.DmsV1.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class vh_terceros
    {
        public decimal nit { get; set; }
        public string nombres { get; set; }
        public string direccion { get; set; }
        public string telefono_1 { get; set; }
        public string telefono_2 { get; set; }
        public string celular { get; set; }
        public string usuario_creo { get; set; }
        public string notas { get; set; }
        public string mail { get; set; }
        public string y_dpto { get; set; }
        public string y_ciudad { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string tipo_identificacion { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha_cotizacion { get; set; }
        public int Id { get; set; }
    }
}
