//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources.ErrorResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageError() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalResources.ErrorResources.MessageError", typeof(MessageError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer representative.
        /// </summary>
        public static string DealerRepresentative {
            get {
                return ResourceManager.GetString("DealerRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DealerShop.
        /// </summary>
        public static string DealerShop {
            get {
                return ResourceManager.GetString("DealerShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conection string.
        /// </summary>
        public static string ErrorConectionStringNull {
            get {
                return ResourceManager.GetString("ErrorConectionStringNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path not suported.
        /// </summary>
        public static string ErrorPathFileNotSuported {
            get {
                return ResourceManager.GetString("ErrorPathFileNotSuported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong shipping format.
        /// </summary>
        public static string ErrorRequestJson {
            get {
                return ResourceManager.GetString("ErrorRequestJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insurance company.
        /// </summary>
        public static string InsuranceCompany {
            get {
                return ResourceManager.GetString("InsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsupported language.
        /// </summary>
        public static string LangugeNotSuported {
            get {
                return ResourceManager.GetString("LangugeNotSuported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} created correctly.
        /// </summary>
        public static string RegisterCreatedOk {
            get {
                return ResourceManager.GetString("RegisterCreatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} data incomplate.
        /// </summary>
        public static string RegisterDataIncomplate {
            get {
                return ResourceManager.GetString("RegisterDataIncomplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} not found.
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} not updated.
        /// </summary>
        public static string RegisterNotUpdate {
            get {
                return ResourceManager.GetString("RegisterNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} not recorded.
        /// </summary>
        public static string RegisterSaveNotComplate {
            get {
                return ResourceManager.GetString("RegisterSaveNotComplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is updated.
        /// </summary>
        public static string RegisterStateUpdate {
            get {
                return ResourceManager.GetString("RegisterStateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} updated correctly.
        /// </summary>
        public static string RegisterUpdateOk {
            get {
                return ResourceManager.GetString("RegisterUpdateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle brand.
        /// </summary>
        public static string VehicleBrand {
            get {
                return ResourceManager.GetString("VehicleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This vehicle is not in the process of being repaired.
        /// </summary>
        public static string VehicleNoRepairProcess {
            get {
                return ResourceManager.GetString("VehicleNoRepairProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle not found.
        /// </summary>
        public static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work order not found.
        /// </summary>
        public static string WokrOrderNotFound {
            get {
                return ResourceManager.GetString("WokrOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work order.
        /// </summary>
        public static string WorkOrder {
            get {
                return ResourceManager.GetString("WorkOrder", resourceCulture);
            }
        }
    }
}
