//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogJobTitleByDealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogJobTitleByDealer()
        {
            this.CatalogDefaultSubOperationByIdJobTitle = new HashSet<CatalogDefaultSubOperationByIdJobTitle>();
            this.JobTilteByWorker = new HashSet<JobTilteByWorker>();
        }
    
        public string IdJobTitle { get; set; }
        public string IdDealerShop { get; set; }
        public string JobTitle { get; set; }
        public int IdDefaultSubOperation { get; set; }
        public string Description { get; set; }
        public bool IsAssignable { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogDefaultSubOperationByIdJobTitle> CatalogDefaultSubOperationByIdJobTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTilteByWorker> JobTilteByWorker { get; set; }
    }
}
