//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogExternalJobsByDealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogExternalJobsByDealer()
        {
            this.ProvidersByExternalJob = new HashSet<ProvidersByExternalJob>();
        }
    
        public int IdExternalJobByDealer { get; set; }
        public int IdOperationByDealer { get; set; }
        public int IdPart { get; set; }
        public int IdAction { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CatalogActions CatalogActions { get; set; }
        public virtual CatalogOperationsByDealer CatalogOperationsByDealer { get; set; }
        public virtual CatalogParts CatalogParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvidersByExternalJob> ProvidersByExternalJob { get; set; }
    }
}
