//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogNotificationType
    {
        public int IdNotificationType { get; set; }
        public string NotificationType { get; set; }
        public string RegularExpression { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    }
}
