//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogDefaultSubOperationByIdJobTitle
    {
        public int IdDefaultSubOperationByJobTitle { get; set; }
        public int IdSubOperationByDealer { get; set; }
        public string IdJobTitleByDealer { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
    
        public virtual CatalogJobTitleByDealer CatalogJobTitleByDealer { get; set; }
        public virtual CatalogSubOperationByDealer CatalogSubOperationByDealer { get; set; }
    }
}
