//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudCatalogSubOperations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CloudCatalogSubOperations()
        {
            this.CatalogSubOperationByDealer = new HashSet<CatalogSubOperationByDealer>();
        }
    
        public int IdSubOperation { get; set; }
        public int IdOperation { get; set; }
        public int SubOperation { get; set; }
        public string SubOperationTranslate { get; set; }
        public bool HasPhoto { get; set; }
        public Nullable<bool> IsAssignable { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogSubOperationByDealer> CatalogSubOperationByDealer { get; set; }
        public virtual CloudCatalogOperations CloudCatalogOperations { get; set; }
    }
}
