//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudCatalogOperations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CloudCatalogOperations()
        {
            this.CatalogOperationsByDealer = new HashSet<CatalogOperationsByDealer>();
            this.CloudCatalogSubOperations = new HashSet<CloudCatalogSubOperations>();
        }
    
        public int IdOperation { get; set; }
        public int Operation { get; set; }
        public string OperationTransalate { get; set; }
        public bool IsParalell { get; set; }
        public Nullable<double> CumulativeProgress { get; set; }
        public bool HasPhoto { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogOperationsByDealer> CatalogOperationsByDealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CloudCatalogSubOperations> CloudCatalogSubOperations { get; set; }
    }
}
