//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLogs
    {
        public int IdNotificationLog { get; set; }
        public string NotificationName { get; set; }
        public string NameRecipientsType { get; set; }
        public string FillterRecipenttype { get; set; }
        public string Destination { get; set; }
        public string Provaider { get; set; }
        public string MessageSend { get; set; }
        public string TitleMessage { get; set; }
        public string MessageErrorProvaider { get; set; }
        public string TypeNotification { get; set; }
        public bool IsSend { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
    }
}
