//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationErpErrors
    {
        public int IdNotificationErpError { get; set; }
        public string TableName { get; set; }
        public string EntityUpdateJson { get; set; }
        public string ErrorGenerate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedById { get; set; }
    }
}
