//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidersByExternalJob
    {
        public int IdProviderByExernalJob { get; set; }
        public int IdExternalJob { get; set; }
        public int IdProvider { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CatalogExternalJobsByDealer CatalogExternalJobsByDealer { get; set; }
        public virtual CatalogProviders CatalogProviders { get; set; }
    }
}
