//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOperationByWorkOrder
    {
        public int IdSubOperationByWorkOrder { get; set; }
        public int IdOperationByWorkOrder { get; set; }
        public int IdSubOperationByDealer { get; set; }
        public string AssignedTo { get; set; }
        public string AssignedById { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
        public double SubOperationTime { get; set; }
        public double OperationTimePercentage { get; set; }
        public Nullable<double> WorkedTime { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CatalogSubOperationByDealer CatalogSubOperationByDealer { get; set; }
        public virtual OperationByWorkOrder OperationByWorkOrder { get; set; }
    }
}
