//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.QuoteRequest = new HashSet<QuoteRequest>();
            this.WorkOrders = new HashSet<WorkOrders>();
        }
    
        public string IdVinNumber { get; set; }
        public string IdCountry { get; set; }
        public int IdCity { get; set; }
        public Nullable<int> IdVehicleType { get; set; }
        public Nullable<int> IdVehicleServiceType { get; set; }
        public Nullable<int> IdInsuranceCompany { get; set; }
        public int IdVehicleModel { get; set; }
        public Nullable<System.DateTime> SaleGuaranteeAt { get; set; }
        public Nullable<int> GuaranteedSaleDistanceTraveled { get; set; }
        public decimal IdCustomerOwner { get; set; }
        public string DealerCity { get; set; }
        public string DealerVehicleModel { get; set; }
        public string Plate { get; set; }
        public int ModelYear { get; set; }
        public string Color { get; set; }
        public Nullable<int> LastMileage { get; set; }
        public Nullable<bool> HasPhoto { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CloudCatalogCities CloudCatalogCities { get; set; }
        public virtual CloudCatalogCountries CloudCatalogCountries { get; set; }
        public virtual CloudCatalogInsuranceCompanies CloudCatalogInsuranceCompanies { get; set; }
        public virtual CloudCatalogVehicleModels CloudCatalogVehicleModels { get; set; }
        public virtual CloudCatalogVehiclesServiceTypes CloudCatalogVehiclesServiceTypes { get; set; }
        public virtual CloudCatalogVehicleTypes CloudCatalogVehicleTypes { get; set; }
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteRequest> QuoteRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrders> WorkOrders { get; set; }
    }
}
