//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystimeDataAcces.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.JobsByWorkOrder = new HashSet<JobsByWorkOrder>();
            this.OperationByWorkOrder = new HashSet<OperationByWorkOrder>();
            this.Quotes = new HashSet<Quotes>();
            this.WorkOrderDetails = new HashSet<WorkOrderDetails>();
            this.WorkOrderNotificationByCustomer = new HashSet<WorkOrderNotificationByCustomer>();
            this.WorkOrderTracking = new HashSet<WorkOrderTracking>();
        }
    
        public decimal IdWorkOrder { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<int> IdCatalogWorkLevel { get; set; }
        public string IdDealerShop { get; set; }
        public string IdVinNumber { get; set; }
        public Nullable<int> IdPhysicalTag { get; set; }
        public Nullable<int> IdErpQuote { get; set; }
        public Nullable<int> IdCurrentOperation { get; set; }
        public string IdCurrentWorker { get; set; }
        public string IdSalesRepresentative { get; set; }
        public Nullable<int> IdInsuranceCompany { get; set; }
        public decimal IdCustomer { get; set; }
        public Nullable<System.DateTime> OpenOtAt { get; set; }
        public Nullable<System.DateTime> EnteredAt { get; set; }
        public Nullable<System.DateTime> PromisedAt { get; set; }
        public Nullable<System.DateTime> AuthorizedAt { get; set; }
        public Nullable<System.DateTime> PartsCompletedAt { get; set; }
        public Nullable<System.DateTime> ReadyToPickUpAt { get; set; }
        public Nullable<System.DateTime> WarrantyAt { get; set; }
        public Nullable<int> GuaranteedDistanceTraveled { get; set; }
        public Nullable<System.DateTime> PickedUpAt { get; set; }
        public Nullable<System.DateTime> InvoicedAt { get; set; }
        public bool HasTotalLoss { get; set; }
        public string Note { get; set; }
        public Nullable<short> RatingDealer { get; set; }
        public bool IsInsured { get; set; }
        public Nullable<short> RatingInsuranceCompany { get; set; }
        public string FeedBack { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
        public Nullable<bool> IsInvoiced { get; set; }
        public Nullable<bool> IsIncludedInReports { get; set; }
    
        public virtual CatalogWorkLevel CatalogWorkLevel { get; set; }
        public virtual CloudCatalogDealerShops CloudCatalogDealerShops { get; set; }
        public virtual CloudCatalogInsuranceCompanies CloudCatalogInsuranceCompanies { get; set; }
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobsByWorkOrder> JobsByWorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationByWorkOrder> OperationByWorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotes> Quotes { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderDetails> WorkOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderNotificationByCustomer> WorkOrderNotificationByCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderTracking> WorkOrderTracking { get; set; }
    }
}
