//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources.ModelResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnotations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalResources.ModelResources.DataAnotations", typeof(DataAnotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for address.
        /// </summary>
        public static string AdressMaxLegthExceeded {
            get {
                return ResourceManager.GetString("AdressMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  alias.
        /// </summary>
        public static string AliasMaxLegthExceeded {
            get {
                return ResourceManager.GetString("AliasMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country required.
        /// </summary>
        public static string CountryRequerid {
            get {
                return ResourceManager.GetString("CountryRequerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email does not contain a correct format.
        /// </summary>
        public static string EmailIncorrectFormat {
            get {
                return ResourceManager.GetString("EmailIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  email.
        /// </summary>
        public static string EmailMaxLegthExceeded {
            get {
                return ResourceManager.GetString("EmailMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for feed back of client.
        /// </summary>
        public static string FeedbackLeghtExceeded {
            get {
                return ResourceManager.GetString("FeedbackLeghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City identifier value outside limits.
        /// </summary>
        public static string IdCityRangeError {
            get {
                return ResourceManager.GetString("IdCityRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City identifier is requiered.
        /// </summary>
        public static string IdCityRequired {
            get {
                return ResourceManager.GetString("IdCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for country.
        /// </summary>
        public static string IdContryMaxLegthExceeded {
            get {
                return ResourceManager.GetString("IdContryMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Identifier value outside limits.
        /// </summary>
        public static string IdCustomerRangeError {
            get {
                return ResourceManager.GetString("IdCustomerRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Identifier is required.
        /// </summary>
        public static string IdCustomerRequeired {
            get {
                return ResourceManager.GetString("IdCustomerRequeired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer identifier value outside limits.
        /// </summary>
        public static string IdDealerRangeError {
            get {
                return ResourceManager.GetString("IdDealerRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer representative identifier value outside limits .
        /// </summary>
        public static string IdDealerRepresentativeRangeError {
            get {
                return ResourceManager.GetString("IdDealerRepresentativeRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer representative identifier is required.
        /// </summary>
        public static string IdDealerRepresentativeRequired {
            get {
                return ResourceManager.GetString("IdDealerRepresentativeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer shop identifier is required.
        /// </summary>
        public static string IdDealerRequired {
            get {
                return ResourceManager.GetString("IdDealerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer Shop identifier value outside limits.
        /// </summary>
        public static string IdDealerShopRangeError {
            get {
                return ResourceManager.GetString("IdDealerShopRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer shop identification is required.
        /// </summary>
        public static string IdDealerShopRequired {
            get {
                return ResourceManager.GetString("IdDealerShopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identity number is required.
        /// </summary>
        public static string IdentityNumberIsRequired {
            get {
                return ResourceManager.GetString("IdentityNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer representative  internal identifier is required.
        /// </summary>
        public static string IdErpDealerRepresentativeIsRequired {
            get {
                return ResourceManager.GetString("IdErpDealerRepresentativeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximun length exceeded for dealer representative internal identifier.
        /// </summary>
        public static string IdErpDealerRepresentativeLegthExceeded {
            get {
                return ResourceManager.GetString("IdErpDealerRepresentativeLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded  for dealer shop internal identifier.
        /// </summary>
        public static string IdErpLegthExceeded {
            get {
                return ResourceManager.GetString("IdErpLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for quote  internal identifier .
        /// </summary>
        public static string IdErpQuoteLegthExceeded {
            get {
                return ResourceManager.GetString("IdErpQuoteLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dealer shop internal identifier is required.
        /// </summary>
        public static string IdErpShop {
            get {
                return ResourceManager.GetString("IdErpShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for work order internal identifier.
        /// </summary>
        public static string IdErpWorkOrderLeghtExceeded {
            get {
                return ResourceManager.GetString("IdErpWorkOrderLeghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuel type identifier value outside limits.
        /// </summary>
        public static string IdFuelTypeRangeError {
            get {
                return ResourceManager.GetString("IdFuelTypeRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender identifier  value outside limits.
        /// </summary>
        public static string IdGenderRangeError {
            get {
                return ResourceManager.GetString("IdGenderRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insurance company identifier  value outside limits.
        /// </summary>
        public static string IdInsuranceCompanyRangeError {
            get {
                return ResourceManager.GetString("IdInsuranceCompanyRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rh identifier  value outside limits.
        /// </summary>
        public static string IdRhRageError {
            get {
                return ResourceManager.GetString("IdRhRageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle model identifier value outside limits.
        /// </summary>
        public static string IdVehcileRangeError {
            get {
                return ResourceManager.GetString("IdVehcileRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle service type identifier value outside limits.
        /// </summary>
        public static string IdVehiccleServiceTypeRangeError {
            get {
                return ResourceManager.GetString("IdVehiccleServiceTypeRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle type identifier value outside limits .
        /// </summary>
        public static string IdVehicleTypeRangeError {
            get {
                return ResourceManager.GetString("IdVehicleTypeRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insurance company rationg value outsite limits.
        /// </summary>
        public static string InsuranceCompanyRatingRangeError {
            get {
                return ResourceManager.GetString("InsuranceCompanyRatingRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded.
        /// </summary>
        public static string MaxLegthExceeded {
            get {
                return ResourceManager.GetString("MaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model year value outside limits.
        /// </summary>
        public static string ModelYearRangeError {
            get {
                return ResourceManager.GetString("ModelYearRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name required.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  name.
        /// </summary>
        public static string NameMaxLegthExceeded {
            get {
                return ResourceManager.GetString("NameMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for note.
        /// </summary>
        public static string NoteLegthExceeded {
            get {
                return ResourceManager.GetString("NoteLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone does not contain a correct format.
        /// </summary>
        public static string PhoneIncorrectFormat {
            get {
                return ResourceManager.GetString("PhoneIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  phone.
        /// </summary>
        public static string PhoneMaxLegthExceeded {
            get {
                return ResourceManager.GetString("PhoneMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mobile does not contain a correct format.
        /// </summary>
        public static string PhoneMobileIncorrectFormat {
            get {
                return ResourceManager.GetString("PhoneMobileIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  mobile.
        /// </summary>
        public static string PhoneMobileMaxLegthExceeded {
            get {
                return ResourceManager.GetString("PhoneMobileMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for plate.
        /// </summary>
        public static string PlateMaxLegthExceeded {
            get {
                return ResourceManager.GetString("PlateMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plate required.
        /// </summary>
        public static string PlateRequired {
            get {
                return ResourceManager.GetString("PlateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for progress message.
        /// </summary>
        public static string ProggresMessageLengthExceeded {
            get {
                return ResourceManager.GetString("ProggresMessageLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shop Rating value outsite limits.
        /// </summary>
        public static string ShopRaitngRangeError {
            get {
                return ResourceManager.GetString("ShopRaitngRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  tax identification number(TIN).
        /// </summary>
        public static string TINMaxLegthExceeded {
            get {
                return ResourceManager.GetString("TINMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax identification number(TIN) is required.
        /// </summary>
        public static string TINReqired {
            get {
                return ResourceManager.GetString("TINReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for vehicle number identifier(VIN) .
        /// </summary>
        public static string VinMaxLegthExceeded {
            get {
                return ResourceManager.GetString("VinMaxLegthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle number identifier(VIN) is required.
        /// </summary>
        public static string VinRequired {
            get {
                return ResourceManager.GetString("VinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website does not contain a correct url format.
        /// </summary>
        public static string WebSiteIncorrectFormat {
            get {
                return ResourceManager.GetString("WebSiteIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum length exceeded for  website.
        /// </summary>
        public static string WebSiteMaxLegthExceeded {
            get {
                return ResourceManager.GetString("WebSiteMaxLegthExceeded", resourceCulture);
            }
        }
    }
}
