//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateAccess.Systimedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSubOperationByDealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogSubOperationByDealer()
        {
            this.SubOperationByWorkOrder = new HashSet<SubOperationByWorkOrder>();
        }
    
        public int IdSubOperationByDealer { get; set; }
        public string IdDealerShop { get; set; }
        public Nullable<int> IdOperationByDealer { get; set; }
        public int IdSubOperation { get; set; }
        public Nullable<int> IdNextSubOperationByDealer { get; set; }
        public string IdDefaultWorker { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsExternalJob { get; set; }
        public Nullable<bool> IsAssignable { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedById { get; set; }
        public Nullable<double> Effort { get; set; }
        public Nullable<double> DefaultPercentage { get; set; }
        public byte[] Version { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CatalogOperationsByDealer CatalogOperationsByDealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubOperationByWorkOrder> SubOperationByWorkOrder { get; set; }
    }
}
